### ISSUE TITLE
项目发展建议

### ISSUE THREAD

**Issue by Zeroto521** [brandonxiang/psm#2]
1. 添加项目测试；
1. 增加 psm 易用度，比如直接使用 `psm ls` 而不是 `python -m psm ls`；
1. 添加到 pypi 的链接，以 **Website** 或者 badge 等形式。

**Comment by brandonxiang** [comment]
周末搞一下，好久没写python，欢迎来pr，大兄弟

**Comment by brandonxiang** [comment]
# roadmap

1. command will be refactered
2. unit test
3. python 2 and 3 compatibility

**Comment by brandonxiang** [comment]
@Zeroto521 不太清楚第三点，怎么弄，我对python社区不太熟悉

**Comment by Zeroto521** [comment]
> @Zeroto521 不太清楚第三点，怎么弄，我对 python 社区不太熟悉

1. Website 
    > ![image](https://user-images.githubusercontent.com/25895405/58703788-6b6f2280-83dc-11e9-82aa-4f2a633c3da8.png)
1. badge
    > ![image](https://user-images.githubusercontent.com/25895405/58703856-a8d3b000-83dc-11e9-83d4-1c919246d681.png)

badge 可以参考[这个项目](https://github.com/Naereen/badges)

**Comment by Zeroto521** [comment]
集成化测试可以借助 travis-ci 或其他测试平台，代码覆盖率可以借助 codecov 或其他平台

**Comment by brandonxiang** [comment]
我这个代码的复杂度没必要搞覆盖率

**Comment by brandonxiang** [comment]
@Zeroto521 我用mac，所以npm ls没啥问题，建议你用mac

**Comment by Zeroto521** [comment]
> @Zeroto521 我用 mac，所以 npm ls 没啥问题，建议你用 mac

> 增加 psm 易用度，比如直接使用 psm ls 而不是 python -m psm ls

这个目的更多是想打造一个全平台的命令行工具，不单单指 Linux 架构下的平台
